# Generated by Django 4.2.7 on 2023-12-12 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='ano_publicacao',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
