# Generated by Django 4.2.7 on 2023-12-12 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0002_livro_ano_publicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='avaliacao',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
