# Generated by Django 4.2.7 on 2023-12-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0004_alter_livro_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
